### ISSUE TITLE
Recurrent `ModuleNotFoundError`

### ISSUE THREAD

**Issue by adrienbanse** [dataforgoodfr/12_genai_impact#29]
It's probably very basic but any idea why I have to run `poetry install --all-extras --with dev,docs ` everytime I make a change in the code to be able to run my `__main__.py` script? Otherwise I very often get `ModuleNotFoundError: No module named 'genai_impact'`.

**Comment by LucBERTON** [comment]
Do you get the error once you run your main script or is it a message displayed by your IDE ?

The other day I had a problem with VS Code that could be similar. 
To solve it in VS Code I did : `Ctrl + Shift + P,` searched for `Python: Select Interpreter` and selected the python interpreter from my venv file.  



If it's not solved, please share your script, I'll see If I have the same issue

**Comment by adrienbanse** [comment]
It's solved thanks 🙏
