### ISSUE TITLE
Model characteristics dataset

### ISSUE THREAD

**Issue by samuelrince** [dataforgoodfr/12_genai_impact#3]
## Description

To compute the impacts of a query, we need some characteristics of the model that was used. Especially in the case of LLMs we need the total count of parameters.

## Solution

A CSV or JSON file to store all known models and metadata like the total parameters count.

### Proprietary models

In many cases, we don't know the underlying architecture of models. thus we will need to guesstimate it (see issue #1 for OpenAI). The estimation can be based on performance achieved by this models in various leaderboards compared to open-weight models. It is crucial to keep the source of this assessment because it influences a lot the impacts.

### Total parameters vs active parameters

In the case of mixture of experts models we can definie the active parameters count as the sum of all active/used parameters to run the computation. (example with [mixtral](https://docs.mistral.ai/models/#sizes)).

**Comment by AndreaLeylavergne** [comment]
I can work on this issue. Is there anyone else to work with me? Is there any information already available so that i can better understand what is excepted here ?

**Comment by samuelrince** [comment]
Found in my notes: https://docs.google.com/spreadsheets/d/1O5KVQW1Hx5ZAkcg8AIRjbQLQzx2wVaLl0SqUu-ir9Fs/edit#gid=1158069878
