### ISSUE TITLE
Package documentation

### ISSUE THREAD

**Issue by LucBERTON** [dataforgoodfr/12_genai_impact#4]
## Description

Write a clear documentation explaining how to install and use the package.

## Solution

- update the README.me file
- create a full package documentation

## Considerations

Technology and format for package documentation to be determined.
e.g. : 
 - notion
 - sphinx (www.sphinx-doc.org)

## Additional context

N/A

**Comment by samuelrince** [comment]
For a modern look and feel, I would recommend [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) ✨
